### ISSUE TITLE
I want to know how to use tencent sdk ?

### ISSUE THREAD

**Issue by keepCreate** [gdtdpt/nativescript-wechat-share-plugin#2]
I attempt to use the tencent live stream sdk,
but I really don't know how to  make the **jar** and **so** files, just like what you use : 
**compile 'com.tencent.mm.opensdk:wechat-sdk-android-without-mta:+'** ?
how to make it and use it to use **functions** and **UI** 
Thank you very much if you have free time to teach me !!!

**Comment by gdtdpt** [comment]
@keepCreate 
你是说直播sdk？我没有用过，看了会文档，似乎不能直接从jcenter配置，需要手动下载开发包倒入，我看的文档在[这里](https://www.qcloud.com/document/product/454/7877)，希望对你有帮助。
