### ISSUE TITLE
Could you please tell me the meaning of /*YOUR_WECHAT_APP_ID*/

### ISSUE THREAD

**Issue by wanpeng2008** [gdtdpt/nativescript-wechat-share-plugin#3]
Sorry for the naive question. Could you please tell me the meaing of /*YOUR_WECHAT_APP_ID*/, and how to get it? Thanks very much

**Comment by gdtdpt** [comment]
@wanpeng2008 你好，
这个是微信应用ID，如果想从外部分享内容到微信中必须在[这里](https://open.weixin.qq.com/)注册你的应用，审核完成后会在应用管理里看到微信应用ID，就是这个YOUR_WECHAT_APP_ID要填的内容。

**Comment by wanpeng2008** [comment]
@gdtdpt 非常感谢您如此及时的答复。我将去申请一个APP_ID来学习使用您的插件，再次感谢您给我们提供了这么有价值的插件。
