### ISSUE TITLE
为什么我分享到朋友圈或者微信好友不能弹出微信界面

### ISSUE THREAD

**Issue by acqj** [gdtdpt/nativescript-wechat-share-plugin#4]
我点击分享到朋友圈或者微信好友 不能弹出微信界面 就直接返回 "message has been sent successfully"
然后什么也没有发生
换了一台手机弹出了界面 分享到朋友圈是可以使用的 但是分享给好友弹出好友列表 点击好友没有反应 没有发送给好友 界面也没消失 点击好友完全没反应

**Comment by acqj** [comment]
@gdtdpt  希望能帮忙分析一下问题

**Comment by gdtdpt** [comment]
@acqj 不好意思，这个问题帮不了你，这个库我已经不维护了。我对nativescript这个框架没什么兴趣，这个库之所以存在是因为以前有相关的项目。如果你有兴趣希望继续维护，我可以把这个库转给你。
